// Generated by tools/build-pages.mjs. This file may be replaced at deploy time.
(() => {
  const deploymentConfig = {
    "leaderboard": "https://tiny-strike-service.guyz-apps.workers.dev/api/leaderboard",
    "websocket": "wss://tiny-strike-service.guyz-apps.workers.dev/ws"
  };
  globalThis.TINY_STRIKE_API = Object.freeze({
    ...(globalThis.TINY_STRIKE_API || {}),
    ...deploymentConfig,
  });
})();
